### ISSUE TITLE
ShowBackingValue.Never does not work

### ISSUE THREAD

**Issue by masonwheeler** [Siccity/xNode#270]
1. Create a node class
2. Put a port on it with `ShowBackingValue.Never` in the `Input` or `Output` attribute
3. Add that node to a graph
4. Mouse over the port

Expected: No tooltip shows up, because it was explicitly told to never show.
Observed: The tooltip shows up anyway.

**Comment by Wizardsxz** [comment]
I believe "never show" is explicitly about displaying the actual serialized field of the node and is unrelated to the tooltip by design.

If you want to hide the tooltip you can go to `NodeEditorGUI.cs` and remove the call to `DrawTooltip()` from `NodeEditorWindow.OnGUI` and tooltips won't be shown on hover

**Comment by Siccity** [comment]
To avoid editing the core, you can also create a custom node graph editor, and override GetPortTooltip. More info on custom node graphs in the wiki.
