### ISSUE TITLE
Is there any tools export  to json or lua?

### ISSUE THREAD

**Issue by huanghaobin** [Siccity/xNode#340]

**Comment by Esildor** [comment]
XNode is just ScriptableObjects, so you [use Unity's](https://docs.unity3d.com/Manual/JSONSerialization.html) `JsonUtility.ToJson(someGraphAsset)`. It's not super feature-rich and might not help you a ton since Unity just serializes the instance ID of serialized `UnityEngine.Object` so the linking of nodes might be hard. 

What's your use case?

**Comment by Siccity** [comment]
Not currently, no. But you can implement it using JsonUtility or Newtonsoft.Json
